import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillGithub} from 'react-icons/ai'
import {AiFillLinkedin} from 'react-icons/ai'
import Image from 'next/image'
import fotoEnzo from '../public/enzocam.png'
///////////////////////////////////////////
import codePng from '../public/code.png'
import designPng from '../public/design.png'
import consultPng from '../public/consulting.png'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-inter px-10'>
        <section className='min-h-screen'>
          <nav className='py-8 mb-6 flex justify-between'>
            <h1 className='text-2xl font-bold'>CE</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a href='#' className='text-white text-lg px-4 py-2 rounded-md ml-4 resume'>Resume</a>
              </li>
            </ul>
          </nav>
        
          <div className='text-center'>
            <div className='relative mx-auto bg-gradient-to-t from-black to-gray-900 mb-4 rounded-3xl w-60 h-80 overflow-hidden'>
              <Image src={fotoEnzo} fill alt='FotoEnzo'/>
            </div>

            <h2 className='text-4xl py-2 text-red-700 font-bold'>Enzo Cámera</h2>
            <h3 className='text-2xl py-2'>Frontend Developer</h3>
            <p className='text-md text-lg mt-3 mb-2 leading-8 text-gray-800'>
              Estudiante autodidacta, con la constancia y disciplina de aprender y mejorar día a día.               
            </p>
            <p className='text-md text-lg py-2 leading-8 text-gray-800 mb-6'>
              Interesado en poner a prueba mis conocimientos, aportar a mis pares con buen desempeño y
              cumplir con las responsabilidades asignadas.
            </p>
            <div className='text-5xl flex justify-center gap-16 py-2'>
              <a href='https://www.linkedin.com/in/enzo-camera/' target="blank">
                <AiFillLinkedin />
              </a>
              <a href='https://github.com/EnzoCam7' target="blank">
                <AiFillGithub />
              </a>
            </div>
          </div>
        </section>

        <section>
          <h3 className='text-3xl font-bold py-1 mb-2 text-center'>Skills</h3>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={codePng} width={100} height={100} alt='Codepng' className='mx-auto' />

              <h3 className='py-4 text-red-700 text-3xl'>Frontend</h3>
              <p className='text-gray-800 text-xl py-1'>HTML5</p>
              <p className='text-gray-800 text-xl py-1'>CSS3</p>
              <p className='text-gray-800 text-xl py-1'>JavaScript</p>
              <p className='text-gray-800 text-xl py-1'>React.js</p>
              <p className='text-gray-800 text-xl py-1'>Next.js</p>
              <p className='text-gray-800 text-xl py-1'>Tailwind CSS</p>
              <p className='text-gray-800 text-xl py-1'>Styled components</p>
            </div>
            
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={consultPng} width={100} height={100} alt='Codepng' className='mx-auto' />

              <h3 className='py-4 text-red-700 text-3xl'>Backend - Databases</h3>
              <p className='text-gray-800 text-xl py-1'>Node.js</p>
              <p className='text-gray-800 text-xl py-1'>Express.js</p>
              <p className='text-gray-800 text-xl py-1'>Mongo DB</p>
              <p className='text-gray-800 text-xl py-1'>MySQL</p>
              <p className='text-gray-800 text-xl py-1'>PostgreSQL</p>
            </div>
            
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={designPng} width={100} height={100} alt='Codepng' className='mx-auto' />

              <h3 className='py-4 text-red-700 text-3xl'>Others</h3>
              <p className='text-gray-800 text-xl py-1'>Figma</p>
              <p className='text-gray-800 text-xl py-1'>NPM</p>
              <p className='text-gray-800 text-xl py-1'>SCRUM</p>
              <p className='text-gray-800 text-xl py-1'>Git & Github</p>
              <p className='text-gray-800 text-xl py-1'>Strapi CMS</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 text-center'>Proyectos Web</h3>
          </div>
        </section>
      </main>

    </div>
  )
}
