import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillGithub} from 'react-icons/ai'
import {AiFillLinkedin} from 'react-icons/ai'
import Image from 'next/image'
import fotoEnzo from '../public/enzocam.png'
///////////////////////////////////////////
import codePng from '../public/code.png'
import designPng from '../public/design.png'
import consultPng from '../public/consulting.png'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-inter px-10'>
        <section className='min-h-screen'>
          <nav className='py-8 mb-6 flex justify-between'>
            <h1 className='text-2xl font-bold'>CE</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a href='#' className='text-white text-lg px-4 py-2 rounded-md ml-4 resume'>Resume</a>
              </li>
            </ul>
          </nav>
        
          <div className='text-center'>
            <div className='relative mx-auto bg-gradient-to-t from-black to-gray-900 mb-4 rounded-3xl w-60 h-80 overflow-hidden'>
              <Image src={fotoEnzo} fill alt='FotoEnzo'/>
            </div>

            <h2 className='text-4xl py-2 text-red-700 font-bold'>Enzo Cámera</h2>
            <h3 className='text-2xl py-2'>Frontend Developer</h3>
            <p className='text-md text-lg py-5 leading-8 text-gray-800'>
              Estudiante autodidacta, basado en la constancia de todos los dias y con habilidades en las tecnologías más solicitadas. 
              <br></br>
              Interesado en poner a prueba mis conocimientos, aportar a mis pares con buen desempeño y
              cumplir con las responsabilidades asignadas.
            </p>
            <div className='text-5xl flex justify-center gap-16 py-2'>
              <a href='https://www.linkedin.com/in/enzo-camera/' target="blank">
                <AiFillLinkedin />
              </a>
              <a href='https://github.com/EnzoCam7' target="blank">
                <AiFillGithub />
              </a>
            </div>
          </div>
        </section>

        <section>
          <h3 className='text-3xl font-bold py-1 mb-2 text-center'>Skills</h3>
          <div>
            <Image src={codePng} width={100} height={100} alt='Codepng' />
          </div>
        </section>
      </main>

    </div>
  )
}
