import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillGithub} from 'react-icons/ai'
import {AiFillLinkedin} from 'react-icons/ai'
import Image from 'next/image'
import fotoEnzo from '../public/enzocam.png'
///////////////////////////////////////////
import codePng from '../public/code.png'
import designPng from '../public/design.png'
import consultPng from '../public/consulting.png'
///////////////////////////////////////////
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
///////////////////////////////////////////
import { useState } from 'react'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-inter px-10 md:px-20 lg:px-40'>
        <section className='min-h-fit mb-10'>
          <nav className='py-8 mb-6 flex justify-between lg:mb-12 lg:mt-2'>
            <h1 className='text-2xl font-bold lg:text-4xl'>CE</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' />
              </li>
              <li>
                <a href='#' className='text-white text-lg px-4 py-2 rounded-md ml-4 resume'>Resume</a>
              </li>
            </ul>
          </nav>
        
          <div className='text-center'>
            <div className='relative mx-auto bg-gradient-to-t from-black to-gray-900 mb-4 rounded-3xl w-60 h-80 overflow-hidden'>
              <Image src={fotoEnzo} fill alt='FotoEnzo'/>
            </div>

            <h2 className='text-4xl py-2 text-red-700 font-bold md:text-5xl'>Enzo Cámera</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Frontend Developer</h3>
            <p className='text-md text-lg mt-3 mb-2 leading-8 text-gray-800 md:text-xl md:w-3/5 lg:w-5/6 md:mx-auto dark:text-white'>
              Estudiante autodidacta, con la constancia y disciplina de aprender y mejorar día a día.               
            </p>
            <p className='text-md text-lg py-2 leading-8 text-gray-800 mb-6 md:text-xl md:w-3/5 md:mx-auto dark:text-white'>
              Interesado en poner a prueba mis conocimientos, aportar a mis pares con buen desempeño y
              cumplir con las responsabilidades asignadas.
            </p>
            <div className='text-5xl flex justify-center gap-16 py-2 md:text-6xl md:mb-0 dark:text-white'>
              <a href='https://www.linkedin.com/in/enzo-camera/' target="blank">
                <AiFillLinkedin />
              </a>
              <a href='https://github.com/EnzoCam7' target="blank">
                <AiFillGithub />
              </a>
            </div>
          </div>
        </section>

        <section className='mb-6'>
          <h3 className='text-4xl font-bold py-1 mb-2 text-center dark:text-white lg:mt-8'>Skills</h3>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={designPng} width={100} height={100} alt='skillsLogo'  className='mx-auto'/>

              <h3 className='py-4 text-red-700 text-3xl'>Frontend</h3>
              <p className='text-gray-800 text-xl py-1'>HTML5</p>
              <p className='text-gray-800 text-xl py-1'>CSS3</p>
              <p className='text-gray-800 text-xl py-1'>JavaScript</p>
              <p className='text-gray-800 text-xl py-1'>React.js</p>
              <p className='text-gray-800 text-xl py-1'>Next.js</p>
              <p className='text-gray-800 text-xl py-1'>Tailwind CSS</p>
              <p className='text-gray-800 text-xl py-1'>Styled components</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={codePng} width={100} height={100} alt='skillsLogo' className='mx-auto' />

              <h3 className='py-4 text-red-700 text-3xl'>Backend - Databases</h3>
              <p className='text-gray-800 text-xl py-1'>Node.js</p>
              <p className='text-gray-800 text-xl py-1'>Express.js</p>
              <p className='text-gray-800 text-xl py-1'>Mongo DB</p>
              <p className='text-gray-800 text-xl py-1'>MySQL</p>
              <p className='text-gray-800 text-xl py-1'>PostgreSQL</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consultPng} width={100} height={100} alt='skillsLogo'  className='mx-auto'/>

              <h3 className='py-4 text-red-700 text-3xl'>Others</h3>
              <p className='text-gray-800 text-xl py-1'>Figma</p>
              <p className='text-gray-800 text-xl py-1'>NPM</p>
              <p className='text-gray-800 text-xl py-1'>SCRUM</p>
              <p className='text-gray-800 text-xl py-1'>Git & Github</p>
              <p className='text-gray-800 text-xl py-1'>Strapi CMS</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 text-center dark:text-white lg:text-4xl lg:font-bold'>Proyectos Web</h3>
            <p className='text-md py-2 leading-8 lg:w-2/3 mx-auto text-gray-800 dark:text-white text-center md:text-2xl'>
              Un par de proyectos tanto <span className='text-red-700'>personales</span> como <span className='text-red-700'>profesionales</span> en los cuales puse
              en práctica lo aprendido de cada tecnología. 
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className="basis-1/3 flex-1">
              <Image src={web1} alt='Imagen del proyecto' className='rounded-lg object-cover' width={'100%'} height={'100%'}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} alt='Imagen del proyecto' className='rounded-lg object-cover' width={'100%'} height={'100%'}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} alt='Imagen del proyecto' className='rounded-lg object-cover' width={'100%'} height={'100%'}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} alt='Imagen del proyecto' className='rounded-lg object-cover' width={'100%'} height={'100%'}/>
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image src={web5} alt='Imagen del proyecto' className='rounded-lg object-cover' width={'100%'} height={'100%'}/>
            </div> */}
            <div className="basis-1/3 flex-1">
              <Image src={web5} alt='Imagen del proyecto' className='rounded-lg object-cover' width={'100%'} height={'100%'}/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} alt='Imagen del proyecto' className='rounded-lg object-cover' width={'100%'} height={'100%'}/>
            </div>
          </div>
        </section>
      </main>

    </div>
  )
}
